In [46]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [47]:
# Sentences
sentences = ['the glass of milk',
             'the glass of juice',
             'the cup of tea',
             'I am a good boy',
             'I am a good developer',
             'understand the meaning of words',
             'your videos are good'
]

In [48]:
# Initializing Vocabulary Dictionary Size
vocabSize = 10000

In [49]:
# One Hot Representation
oneHotRep = []

for words in sentences:
    encoded = one_hot(words, vocabSize)
    oneHotRep.append(encoded)
print(oneHotRep)

[[435, 4062, 7696, 825], [435, 4062, 7696, 4006], [435, 4819, 7696, 3363], [5539, 507, 4189, 7225, 1271], [5539, 507, 4189, 7225, 3049], [642, 435, 7415, 7696, 4918], [4273, 8138, 6973, 7225]]


In [50]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [51]:
# Every Sentence Should have Equal No of Words (PadSequence Needs List of Lists)
sentenceLength = 8
embeddedDocs = pad_sequences(oneHotRep, padding='pre', maxlen=sentenceLength)
print(embeddedDocs)

# Every sentence should become of size 8 and missing no of words should be filled with index 0 At Starting(padding = pre)

[[   0    0    0    0  435 4062 7696  825]
 [   0    0    0    0  435 4062 7696 4006]
 [   0    0    0    0  435 4819 7696 3363]
 [   0    0    0 5539  507 4189 7225 1271]
 [   0    0    0 5539  507 4189 7225 3049]
 [   0    0    0  642  435 7415 7696 4918]
 [   0    0    0    0 4273 8138 6973 7225]]


In [52]:
dimensions = 10

In [53]:
#Creating a NLP model with adding embedding layer with adam optimiser and perfonce matrix as Mean Squared Error(MSE)
model = Sequential()
model.add(Embedding(vocabSize, dimensions, input_length=sentenceLength))
model.compile('adam', 'mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [54]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
predictions =  model.predict(embeddedDocs)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
[[[ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923
    0.00864817 -0.01084774  0.01281748  0.04962778 -0.04993507]
  [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923
    0.00864817 -0.01084774  0.01281748  0.04962778 -0.04993507]
  [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923
    0.00864817 -0.01084774  0.01281748  0.04962778 -0.04993507]
  [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923
    0.00864817 -0.01084774  0.01281748  0.04962778 -0.04993507]
  [-0.03847308  0.01100523  0.01592172 -0.0337284  -0.00830729
   -0.00886836 -0.0433234   0.03183264  0.01729456 -0.04379257]
  [ 0.00872841  0.00507609 -0.01861483  0.02675146  0.01504958
    0.03768008  0.01583824  0.03765495 -0.00347134  0.02109578]
  [-0.03324772 -0.01691837  0.02333868 -0.04073276 -0.04270167
    0.02586219  0.00546283  0.00238335 -0.04005343  0.01651145]
  [ 0.02380497 -0.00197599 -0.0182668   0.04680142  0.01815233
   -0.035

In [56]:
# Embedded Layer Of First Sentence
predictionFirst = model.predict(embeddedDocs)[0]
print(predictionFirst)
# Each Word in A Sentence is Converted into Dimension of 10 (10 Rows)(8 Words Means 80 Rows)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923  0.00864817
  -0.01084774  0.01281748  0.04962778 -0.04993507]
 [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923  0.00864817
  -0.01084774  0.01281748  0.04962778 -0.04993507]
 [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923  0.00864817
  -0.01084774  0.01281748  0.04962778 -0.04993507]
 [ 0.02846345  0.01208336 -0.03658853 -0.0119767   0.01642923  0.00864817
  -0.01084774  0.01281748  0.04962778 -0.04993507]
 [-0.03847308  0.01100523  0.01592172 -0.0337284  -0.00830729 -0.00886836
  -0.0433234   0.03183264  0.01729456 -0.04379257]
 [ 0.00872841  0.00507609 -0.01861483  0.02675146  0.01504958  0.03768008
   0.01583824  0.03765495 -0.00347134  0.02109578]
 [-0.03324772 -0.01691837  0.02333868 -0.04073276 -0.04270167  0.02586219
   0.00546283  0.00238335 -0.04005343  0.01651145]
 [ 0.02380497 -0.00197599 -0.0182668   0.04680142  0.01815233 -0.03514946
  -0.0325502 