In [2]:
import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):
  def __init__(self, numOfFeatures):
    super().__init__()
    self.linear = nn.Linear(numOfFeatures, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [6]:
features = torch.rand(10,5)
print(features)
model = Model(features.shape[1])
model(features)

tensor([[0.0139, 0.2681, 0.5150, 0.1726, 0.0529],
        [0.6637, 0.1258, 0.3792, 0.6325, 0.1730],
        [0.1833, 0.5189, 0.5324, 0.6961, 0.7937],
        [0.5753, 0.1439, 0.1876, 0.3010, 0.4270],
        [0.7524, 0.0320, 0.6214, 0.7016, 0.4919],
        [0.7354, 0.1238, 0.2185, 0.7813, 0.6843],
        [0.3154, 0.0992, 0.2394, 0.7635, 0.8218],
        [0.3709, 0.2941, 0.7767, 0.4406, 0.3654],
        [0.1376, 0.5329, 0.2600, 0.3695, 0.8277],
        [0.1745, 0.6758, 0.9658, 0.9683, 0.1393]])


tensor([[0.4140],
        [0.4869],
        [0.4057],
        [0.4476],
        [0.4837],
        [0.4822],
        [0.4602],
        [0.4259],
        [0.3820],
        [0.4322]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[ 0.1525, -0.3712, -0.0999,  0.3303, -0.1866]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([-0.2457], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
class Model2(nn.Module):
  def __init__(self, numOfFeatures):
    super().__init__()
    self.linear1 = nn.Linear(numOfFeatures, 3) # Hidden Layer
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out


In [16]:
x = torch.rand(20, 5)
model2 = Model2(x.shape[1])
model2(x)

tensor([[0.4903],
        [0.3702],
        [0.4264],
        [0.3870],
        [0.4409],
        [0.4443],
        [0.3648],
        [0.4096],
        [0.4178],
        [0.4025],
        [0.4924],
        [0.4506],
        [0.4188],
        [0.4266],
        [0.4799],
        [0.4430],
        [0.4000],
        [0.4433],
        [0.4209],
        [0.4286]], grad_fn=<SigmoidBackward0>)

In [17]:
print(model2.linear1.weight)
print(model2.linear1.bias)
print()
print(model2.linear2.weight)
print(model2.linear2.bias)

Parameter containing:
tensor([[ 0.2943,  0.2617,  0.2348, -0.3233,  0.4280],
        [-0.3275,  0.3469, -0.1640, -0.2385, -0.3255],
        [-0.0322,  0.0714, -0.1558, -0.2662, -0.0284]], requires_grad=True)
Parameter containing:
tensor([-0.0377, -0.2718, -0.0363], requires_grad=True)

Parameter containing:
tensor([[ 0.5564, -0.3544, -0.5425]], requires_grad=True)
Parameter containing:
tensor([-0.5561], requires_grad=True)


In [18]:
summary(model2, input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [19]:
class Model3(nn.Module):
  def __init__(self, numOfFeatures):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(numOfFeatures, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, x):
    return self.network(x)


In [20]:
model3 = Model3(x.shape[1])
model3(x)

tensor([[0.3617],
        [0.4032],
        [0.3880],
        [0.4015],
        [0.3601],
        [0.3973],
        [0.4065],
        [0.3626],
        [0.3738],
        [0.3780],
        [0.3519],
        [0.3602],
        [0.3936],
        [0.3732],
        [0.3445],
        [0.3851],
        [0.4015],
        [0.3787],
        [0.3614],
        [0.3628]], grad_fn=<SigmoidBackward0>)