In [47]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data (1).csv


In [132]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [49]:
df = pd.read_csv('/content/data.csv')

In [50]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [51]:
df.shape

(569, 33)

In [52]:
x = df.drop(['Unnamed: 32', 'id', 'diagnosis'], axis=1)
y = df['diagnosis']

In [54]:
print(x)
print(y)
print(x.shape)
print(y.shape)

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]
0      M
1      M
2      M
3      M
4      M
      

In [55]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.2, random_state=2)

In [56]:
print(xTrain.shape)
print(xTest.shape)
print(yTrain.shape)
print(yTest.shape)

(455, 30)
(114, 30)
(455,)
(114,)


### Scaling

In [57]:
scaler = StandardScaler()
xTrain = scaler.fit_transform(xTrain)
xTest = scaler.transform(xTest)

In [58]:
xTrain

array([[-0.01330339,  1.7757658 , -0.01491962, ..., -0.13236958,
        -1.08014517, -0.03527943],
       [-0.8448276 , -0.6284278 , -0.87702746, ..., -1.11552632,
        -0.85773964, -0.72098905],
       [ 1.44755936,  0.71180168,  1.47428816, ...,  0.87583964,
         0.4967602 ,  0.46321706],
       ...,
       [-0.46608541, -1.49375484, -0.53234924, ..., -1.32388956,
        -1.02997851, -0.75145272],
       [-0.50025764, -1.62161319, -0.527814  , ..., -0.0987626 ,
         0.35796577, -0.43906159],
       [ 0.96060511,  1.21181916,  1.00427242, ...,  0.8956983 ,
        -1.23064515,  0.50697397]])

In [59]:
encoder = LabelEncoder()
yTrain = encoder.fit_transform(yTrain)
yTest = encoder.transform(yTest)

In [60]:
yTrain

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,

* Converting into tensors

In [102]:
xTrainT = torch.from_numpy(xTrain.astype(np.float32))
xTestT = torch.from_numpy(xTest.astype(np.float32))
yTrainT = torch.from_numpy(yTrain.astype(np.float32))
yTestT = torch.from_numpy(yTest.astype(np.float32))

In [103]:
xTrainT.shape

torch.Size([455, 30])

# Defining the model

In [125]:
class NNmodel():
  def __init__(self, X):
    self.weights = torch.rand(x.shape[1], 1, dtype = torch.float32, requires_grad= True) # 30x1
    self.bias = torch.zeros(1, dtype = torch.float32, requires_grad= True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    yPred = torch.sigmoid(z)
    return yPred

  def lossFunc(self, yPred, yTrue):
    eps = 1e-7
    yPred = torch.clamp(yPred, eps, 1 - eps)
    return -(yTrue * torch.log(yPred) + (1 - yTrue) * torch.log(1 - yPred)).mean()



In [122]:
learningRate = 0.1
epochs = 30

# Training Pipeline

In [127]:
model = NNmodel(xTrainT)
print(model.weights)
print(model.weights.shape)
print(model.bias)
print(model.bias.shape)

tensor([[0.0242],
        [0.7745],
        [0.6236],
        [0.5461],
        [0.2421],
        [0.2261],
        [0.3945],
        [0.6051],
        [0.5880],
        [0.9356],
        [0.5406],
        [0.9229],
        [0.4024],
        [0.1543],
        [0.3652],
        [0.7123],
        [0.5433],
        [0.4762],
        [0.7450],
        [0.4053],
        [0.6718],
        [0.3908],
        [0.7070],
        [0.8285],
        [0.7620],
        [0.0565],
        [0.2707],
        [0.0224],
        [0.2436],
        [0.2443]], requires_grad=True)
torch.Size([30, 1])
tensor([0.], requires_grad=True)
torch.Size([1])


# Training Model

In [129]:
for epoch in range(epochs):

    # Forward Pass
    yPred = model.forward(xTrainT)

    # Calculate Loss
    loss = model.lossFunc(yPred, yTrainT)

    # Backpropogation
    loss.backward()

    # Update weights
    with torch.no_grad():
        model.weights.data -= learningRate * model.weights.grad
        model.bias.data    -= learningRate * model.bias.grad

    # Reset gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 1, Loss: 0.7717
Epoch 2, Loss: 0.7635
Epoch 3, Loss: 0.7560
Epoch 4, Loss: 0.7492
Epoch 5, Loss: 0.7429
Epoch 6, Loss: 0.7372
Epoch 7, Loss: 0.7319
Epoch 8, Loss: 0.7271
Epoch 9, Loss: 0.7227
Epoch 10, Loss: 0.7187
Epoch 11, Loss: 0.7150
Epoch 12, Loss: 0.7116
Epoch 13, Loss: 0.7085
Epoch 14, Loss: 0.7056
Epoch 15, Loss: 0.7030
Epoch 16, Loss: 0.7006
Epoch 17, Loss: 0.6984
Epoch 18, Loss: 0.6964
Epoch 19, Loss: 0.6945
Epoch 20, Loss: 0.6928
Epoch 21, Loss: 0.6912
Epoch 22, Loss: 0.6897
Epoch 23, Loss: 0.6884
Epoch 24, Loss: 0.6872
Epoch 25, Loss: 0.6860
Epoch 26, Loss: 0.6849
Epoch 27, Loss: 0.6839
Epoch 28, Loss: 0.6830
Epoch 29, Loss: 0.6822
Epoch 30, Loss: 0.6814


In [130]:
model.weights

tensor([[-0.3269],
        [ 0.1788],
        [ 0.2511],
        [ 0.1563],
        [-0.1905],
        [-0.2975],
        [-0.1453],
        [ 0.0738],
        [ 0.0652],
        [ 0.5304],
        [-0.0373],
        [ 0.1877],
        [-0.1535],
        [-0.2815],
        [-0.1669],
        [ 0.1966],
        [ 0.1042],
        [-0.0528],
        [ 0.1749],
        [-0.1224],
        [ 0.2697],
        [-0.1739],
        [ 0.2975],
        [ 0.3954],
        [ 0.3964],
        [-0.2444],
        [-0.0626],
        [-0.3427],
        [-0.0465],
        [-0.0498]], requires_grad=True)

In [131]:
model.bias

tensor([-0.3958], requires_grad=True)

In [136]:
# model evaluation
with torch.no_grad():
  yPred = model.forward(xTestT)
  yPred = (yPred > 0.9).float()
  accuracy = (yPred == yTestT).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6052631735801697
